#### Importando Librerias Numpy

In [44]:
import numpy as np
import random as rd

###### Creando una lista de 10 Elementos

In [45]:
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

###### Transformando de lista a arrys

In [46]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###### Corroborando el tipo de objeto

In [47]:
type(arreglo)

numpy.ndarray

In [48]:
arreglo.dtype

dtype('int32')

###### Definiendo array de int32 a float32


In [49]:
np.array(arreglo,dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

###### sifue siendo un array de int32

In [50]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###### Promedio con array

In [51]:
promedio= np.mean(arreglo)
promedio

5.5

###### mediana

In [52]:
mediana=np.median(arreglo)
mediana

5.5

###### dsviacion media

In [53]:
desviacion_std=np.std(arreglo)
desviacion_std

2.8722813232690143

In [54]:
arreglo_de_unos=np.ones(20)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [55]:
arreglo_de_unos= arreglo_de_unos.astype(int)
arreglo_de_unos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [56]:
arreglo_de_unos=np.zeros(20)
arreglo_de_unos

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [67]:
arreglo_alearotio=np.random.rand(5)
arreglo_alearotio

array([0.5674547 , 0.50937416, 0.22911829, 0.30003724, 0.18230727])

In [69]:
arreglo_alearotio22=np.random.randint(1,5,5)
arreglo_alearotio22

array([2, 4, 1, 4, 2])

In [71]:
matriz=np.random.rand(3,3)
matriz

array([[0.29477869, 0.65028766, 0.63454911],
       [0.96314312, 0.99127561, 0.79515685],
       [0.94819548, 0.71680647, 0.21732021]])

In [81]:
#                                         Fila Columna
#                                            ^  ^
#                                            |  |
matriz_enteros_1_7=np.random.randint(1,100,(1,10))
matriz_enteros_1_7

array([[ 4, 22, 44, 94,  8,  2, 21, 89, 23, 81]])

<h1 style=color:orange>HOLA</h1>